"""add_model_file_to_sessions

Revision ID: 64581b22152f
Revises: cea9453a5653
Create Date: 2026-05-12 19:14:43.712305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64581b22152f'
down_revision: Union[str, None] = 'cea9453a5653'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_sessions', sa.Column('model_file', sa.String(length=255), server_default='cnn_cheating_model.pth', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exam_sessions', 'model_file')
    # ### end Alembic commands ###
