"""initial_schema

Revision ID: cea9453a5653
Revises: 
Create Date: 2026-05-12 18:12:29.746800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cea9453a5653'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=512), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=32), server_default='idle', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('output_video', sa.String(length=512), nullable=True),
    sa.Column('log_csv', sa.String(length=512), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proctoring_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('verdict', sa.String(length=16), nullable=False),
    sa.Column('cheat_prob', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=32), nullable=True),
    sa.Column('obj_nearby', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('obj_name', sa.String(length=64), nullable=True),
    sa.Column('reasons', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('frame_index', sa.Integer(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_proctoring_events_session_occurred', 'proctoring_events', ['session_id', 'occurred_at'], unique=False)
    op.create_index('ix_proctoring_events_session_verdict_cheating', 'proctoring_events', ['session_id', 'verdict'], unique=False, postgresql_where=sa.text("verdict = 'CHEATING'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_proctoring_events_session_verdict_cheating', table_name='proctoring_events', postgresql_where=sa.text("verdict = 'CHEATING'"))
    op.drop_index('ix_proctoring_events_session_occurred', table_name='proctoring_events')
    op.drop_table('proctoring_events')
    op.drop_table('exam_sessions')
    # ### end Alembic commands ###
