export const MODELS = {
  cnn: {
    name: "Custom CNN",
    emoji: "🧠",
    badge: "BEST MODEL ⭐",
    accuracy: 0.9780,
    f1: 0.9780,
    rocAuc: 0.9995,
    params: "~200K",
    norm: "[0.5, 0.5, 0.5] / [0.5, 0.5, 0.5]",
    file: "cnn_cheating_model.pth",
    strategy: "Trained from scratch — no pretrained weights",
    architecture: [
      "Conv2d(3→32, 3×3) + BatchNorm + ReLU + MaxPool2d(2×2)",
      "Conv2d(32→64, 3×3) + BatchNorm + ReLU + MaxPool2d(2×2)",
      "Conv2d(64→128, 3×3) + BatchNorm + ReLU + MaxPool2d(2×2)",
      "AdaptiveAvgPool2d(1×1)",
      "Flatten → Linear(128→64) + BatchNorm + ReLU + Dropout(0.3)",
      "Linear(64→2) — final classification head",
    ],
    pros: [
      "Lightest model at ~200K parameters",
      "Highest ROC-AUC (0.9995) among all models",
      "Fastest inference — ideal for real-time pipelines",
      "No ImageNet dependency",
      "Lowest memory footprint",
    ],
    cons: [
      "No pretrained features",
      "May underperform on very small datasets",
      "Limited spatial feature hierarchy",
    ],
    color: "#22c55e",
    phase2: "N/A — single-phase training from scratch",
    archCode: `class CustomCNN(nn.Module):
    def __init__(self, num_classes=2):
        super().__init__()
        self.features = nn.Sequential(
            nn.Conv2d(3, 32, 3, padding=1), nn.BatchNorm2d(32), nn.ReLU(), nn.MaxPool2d(2, 2),
            nn.Conv2d(32, 64, 3, padding=1), nn.BatchNorm2d(64), nn.ReLU(), nn.MaxPool2d(2, 2),
            nn.Conv2d(64, 128, 3, padding=1), nn.BatchNorm2d(128), nn.ReLU(), nn.MaxPool2d(2, 2),
        )
        self.pool = nn.AdaptiveAvgPool2d((1, 1))
        self.classifier = nn.Sequential(
            nn.Flatten(),
            nn.Linear(128, 64), nn.BatchNorm1d(64),
            nn.ReLU(), nn.Dropout(0.3),
            nn.Linear(64, num_classes),
        )`,
  },
  resnet18: {
    name: "ResNet18",
    emoji: "🏛️",
    accuracy: 0.9725,
    f1: 0.9725,
    rocAuc: 0.9986,
    params: "~11M",
    norm: "[0.485, 0.456, 0.406] / [0.229, 0.224, 0.225]",
    file: "resnet18_cheating_model.pth",
    strategy: "Transfer learning — freeze backbone → train custom head",
    architecture: [
      "ResNet18 backbone (pretrained on ImageNet1K) — 17 conv layers",
      "Global Average Pooling over spatial feature maps",
      "Custom head: Linear(512→128) + ReLU + Dropout(0.5)",
      "Linear(128→2) — binary classification output",
    ],
    pros: [
      "Strong residual learning",
      "Well-understood architecture",
      "Fast convergence with frozen backbone",
      "Good generalisation from ImageNet",
    ],
    cons: [
      "11M parameters — much heavier than Custom CNN",
      "Requires ImageNet normalisation",
      "Skip connections add complexity",
    ],
    color: "#3b82f6",
    phase2: "Unfreeze full backbone with differential learning rates: head lr=1e-3, backbone lr=1e-5",
  },
  efficientnet: {
    name: "EfficientNet-B0",
    emoji: "⚡",
    accuracy: 0.9780,
    f1: 0.9780,
    rocAuc: 0.9989,
    params: "~5.3M",
    norm: "[0.485, 0.456, 0.406] / [0.229, 0.224, 0.225]",
    file: "efficientnet_cheating.pth",
    strategy: "Transfer learning — freeze features → train classifier head",
    architecture: [
      "EfficientNet-B0 feature extractor (pretrained ImageNet1K)",
      "MBConv blocks with Squeeze-and-Excitation",
      "Adaptive pooling to 1×1 spatial output (1280 channels)",
      "Custom classifier: Linear(1280→256) + ReLU + Dropout(0.4)",
      "Linear(256→2) — binary output",
    ],
    pros: [
      "Compound scaling — efficient accuracy",
      "Matches Custom CNN accuracy at 0.9780",
      "SE blocks improve channel attention",
      "Good balance between accuracy and parameters",
    ],
    cons: [
      "5.3M parameters vs ~200K for Custom CNN",
      "Slightly lower ROC-AUC",
      "MBConv blocks can be slow on CPU",
    ],
    color: "#f59e0b",
    phase2: "Unfreeze features with lr=1e-5 while maintaining classifier lr=1e-3",
  },
  vit: {
    name: "ViT-B/16",
    emoji: "🤖",
    accuracy: 0.9780,
    f1: 0.9780,
    rocAuc: 0.9999,
    params: "~86M",
    norm: "[0.485, 0.456, 0.406] / [0.229, 0.224, 0.225]",
    file: "Vision_Transformer.pth",
    strategy: "Transfer learning — freeze encoder → train classification head",
    architecture: [
      "Patch embedding: 224×224 image → 196 patches of size 16×16",
      "Learnable [CLS] token prepended to patch sequence",
      "Positional embeddings added to patch tokens",
      "12 Transformer encoder blocks (hidden dim 768, heads 12)",
      "Multi-head self-attention (MHSA) + MLP blocks",
      "Custom head: Linear(768→256) + ReLU + Dropout(0.4) + Linear(256→2)",
    ],
    pros: [
      "Highest ROC-AUC of all models at 0.9999",
      "Global self-attention captures long-range dependencies",
      "Excellent for subtle cheating cues",
      "Matches CNN accuracy despite pure attention",
    ],
    cons: [
      "86M parameters — 430× heavier than Custom CNN",
      "Requires large datasets",
      "Slow inference — unsuitable for real-time",
      "High GPU memory usage",
    ],
    color: "#8b5cf6",
    phase2: "Unfreeze last 4 encoder transformer blocks with lr=5e-6 (very conservative)",
  },
};

export const MODEL_COMPARISON = [
  { rank: "1", name: "Custom CNN ⭐", acc: "0.9780", f1: "0.9780", auc: "0.9995", params: "~200K", deploy: "✅ Selected", color: "#22c55e", aucColor: "#22c55e" },
  { rank: "2", name: "EfficientNet-B0", acc: "0.9780", f1: "0.9780", auc: "0.9989", params: "~5.3M", deploy: "—", color: "#f59e0b", aucColor: "#94a3b8" },
  { rank: "3", name: "ViT-B/16", acc: "0.9780", f1: "0.9780", auc: "0.9999", params: "~86M", deploy: "⚠ Too heavy", color: "#8b5cf6", aucColor: "#a78bfa" },
  { rank: "4", name: "MobileNetV2", acc: "0.9753", f1: "0.9753", auc: "0.9982", params: "~3.4M", deploy: "—", color: "#64748b", aucColor: "#94a3b8" },
  { rank: "5", name: "ResNet18", acc: "0.9725", f1: "0.9725", auc: "0.9986", params: "~11M", deploy: "—", color: "#64748b", aucColor: "#94a3b8" },
];